// Article data — mirrors the real kidsnews payloads
const ARTICLES = [
  {
    id: "apr21_apple",
    day: 0,
    title: "Apple Gets a New Boss! Tim Cook Steps Down After 15 Years",
    summary: "Big news from one of the world's most famous companies! Apple announced Tim Cook will step down as CEO on August 31, and John Ternus will take over on September 1. Cook led Apple for nearly 15 years and grew it to be worth about $4 trillion. Ternus, who is 50, has been in charge of building Apple's hardware — iPhones, iPads, MacBooks, AirPods, and the Vision Pro headset. Fun fact: before tech, he was a competitive swimmer!",
    image: "https://img.odcdn.com.br/wp-content/uploads/2026/01/Destaque-John-Ternus-e-Tim-Cook-1920x1080.jpg",
    category: "News",
    source: "Apple Newsroom",
    time: "Apr 21, 2026",
    readMins: 4,
    level: "Sprout",
    xp: 35,
    tag: "Tech",
    keywords: [
      { term: "CEO", def: "Chief Executive Officer — the top boss who runs a company." },
      { term: "unanimously", def: "When everyone in a group agrees on the same thing." },
      { term: "hardware", def: "The physical parts of a computer or gadget you can touch, like a phone's screen." },
      { term: "trillion", def: "A really, really big number — one thousand billions." },
      { term: "chairman", def: "A person who leads a group of company leaders called the board." },
    ],
    quiz: [
      { q: "When will John Ternus become Apple's new CEO?", options: ["August 31", "September 1", "April 20", "January 1"], a: 1 },
      { q: "What will Tim Cook do after stepping down?", options: ["Retire completely", "Become Executive Chairman", "Start a new company", "Move to swim team"], a: 1 },
      { q: "Which product is NOT mentioned as hardware Ternus worked on?", options: ["iPhone", "Vision Pro", "MacBook", "Apple TV channel"], a: 3 },
    ],
    discussion: [
      "If you ran a giant company, what new invention would you ask your team to build first?",
      "Why do you think a company's leader matters so much?",
    ],
  },
  {
    id: "apr21_earthday",
    day: 0,
    title: "Tomorrow Is Earth Day! 10,000+ Events Around the World",
    summary: "Get ready to celebrate our planet! April 22 is Earth Day, and this year's theme is \"Our Power, Our Planet.\" More than 10,000 events are planned around the world — cleanups, tree plantings, science workshops, and marches. In Detroit, families will pack seeds and build rain barrels. In New York, Union Square hosts climate art and kids' activities. At home, you can decorate a flower pot or build a water filter from cotton, sand, charcoal, and gravel!",
    image: "https://www.earthreminder.com/wp-content/uploads/2026/01/earth-day-2026-theme-poster-390x220.jpg",
    category: "News",
    source: "EARTHDAY.ORG",
    time: "Apr 21, 2026",
    readMins: 4,
    level: "Sprout",
    xp: 30,
    tag: "Planet",
    keywords: [
      { term: "Earth Day", def: "A special day every April 22 when people around the world celebrate and help our planet." },
      { term: "environment", def: "Everything around us — air, water, plants, animals, and the land." },
      { term: "rain barrel", def: "A big container that catches rainwater so you can use it for plants later." },
      { term: "filter", def: "Something that cleans water or air by catching the dirty bits." },
      { term: "community", def: "A group of people who live near each other or share something in common." },
    ],
    quiz: [
      { q: "What is this year's Earth Day theme?", options: ["Save the Whales", "Our Power, Our Planet", "Trees First", "One Ocean"], a: 1 },
      { q: "About how many events are planned worldwide?", options: ["100", "1,000", "10,000+", "100,000+"], a: 2 },
      { q: "Which year was the very first Earth Day?", options: ["1950", "1970", "1990", "2000"], a: 1 },
    ],
    discussion: [
      "What's one Earth Day activity you'd do with your family?",
      "If you had to pick ONE small daily habit to help the planet, what would it be?",
    ],
  },
  {
    id: "apr21_moringa",
    day: 0,
    title: "\"Miracle Tree\" Seeds Can Clean 98% of Tiny Plastics From Water!",
    summary: "Scientists just found something amazing: seeds from a tree called moringa can remove almost all the tiny plastic bits from drinking water — even better than the chemicals we normally use. Microplastics are super tiny plastic pieces that carry a negative charge, making them slip through filters. Moringa seed extract works like a magnet, pulling them into bigger clumps that filters can catch. In tests, moringa removed 98.5% of microplastics — and it's natural, cheap, and non-toxic.",
    image: "https://cff2.earth.com/uploads/2026/04/20091800/Moringa-seeds-microplastics.jpg",
    category: "Science",
    source: "ACS Omega",
    time: "Apr 21, 2026",
    readMins: 5,
    level: "Tree",
    xp: 45,
    tag: "Discovery",
    keywords: [
      { term: "microplastics", def: "Plastic pieces so small you sometimes can't even see them." },
      { term: "moringa", def: "A fast-growing tree that grows in warm parts of the world and is nicknamed the 'miracle tree'." },
      { term: "extract", def: "Something useful taken out of a plant or food — like juice from an orange." },
      { term: "biodegradable", def: "Something that breaks down naturally without polluting the Earth." },
      { term: "filter", def: "A tool that catches dirt or bits so clean stuff can pass through." },
    ],
    quiz: [
      { q: "What percentage of microplastics did moringa remove?", options: ["50%", "75%", "98.5%", "100%"], a: 2 },
      { q: "Why do microplastics slip through normal filters?", options: ["They're too big", "They have a negative charge that pushes them apart", "They dissolve in water", "They're invisible"], a: 1 },
      { q: "What's one big advantage of moringa over chemicals?", options: ["It's shiny", "It's biodegradable and non-toxic", "It smells nice", "It's faster"], a: 1 },
    ],
    discussion: [
      "Where have you seen microplastics in the news before?",
      "Why might a natural solution be better than a chemical one for communities with less money?",
    ],
  },
  {
    id: "apr21_muppet",
    day: 0,
    title: "College Student Finds New Dinosaur Species — Meet the \"Murder Muppet\"!",
    summary: "A squished dinosaur skull sat in a museum drawer for 30 years. Now, Virginia Tech senior Simba Srivastava has identified it as a brand-new meat-eating dinosaur species — one that lived three times longer ago than T. rex! He used CT scans to separate the crushed bones and 3D-printed a reconstruction. The dinosaur had huge cheekbones and a short, deep snout. Its official name is Ptychotherates bucculentus, but everyone just calls it the \"Murder Muppet.\"",
    image: "https://img.freepik.com/premium-photo/dinosaur-skull-fossil-closeup_762026-94133.jpg",
    category: "Science",
    source: "Virginia Tech News",
    time: "Apr 21, 2026",
    readMins: 5,
    level: "Sprout",
    xp: 40,
    tag: "Dinosaurs",
    keywords: [
      { term: "fossil", def: "The hardened remains or print of a plant or animal from long, long ago." },
      { term: "CT scan", def: "A super-powered X-ray that makes a 3D picture of what's inside something." },
      { term: "species", def: "A group of living things that are the same kind, like lions or oak trees." },
      { term: "paleontologist", def: "A scientist who studies fossils and ancient life." },
      { term: "carnivorous", def: "Meat-eating." },
    ],
    quiz: [
      { q: "Where was the skull hidden for 30+ years?", options: ["In a cave", "In a museum drawer", "Under a mountain", "In a lab fridge"], a: 1 },
      { q: "What tool helped separate the crushed bones?", options: ["Microscope", "CT scan", "Magnet", "Drill"], a: 1 },
      { q: "Why is it called the 'Murder Muppet'?", options: ["It was found near a Muppets show", "A paleo-artist thought it looked like a Muppet", "It eats muppets", "It was named after a kid"], a: 1 },
    ],
    discussion: [
      "If you discovered a new dinosaur, what silly nickname would you give it?",
      "Why do you think some fossils sit in drawers for decades before anyone studies them?",
    ],
  },
  {
    id: "apr21_barcelona",
    day: 0,
    title: "He's Back! Arthur Fils Wins Barcelona Open After 8-Month Injury",
    summary: "French tennis star Arthur Fils made an incredible comeback! On April 19, the 21-year-old won the Barcelona Open by beating Russia's Andrey Rublev 6-2, 7-6 in the final. Fils had been out for eight months with a serious back injury — many people wondered if he could return. He answered loud and clear, winning six games in a row in the first set and sweeping the tiebreak 7-0. Then he jumped into the famous champion's pool!",
    image: "https://www.barcelonaopenbancsabadell.com/-/media/sites/tournaments/barcelona/news-articles/20260419_fils.png",
    category: "Fun",
    source: "ATP Tour",
    time: "Apr 21, 2026",
    readMins: 4,
    level: "Sprout",
    xp: 30,
    tag: "Sports",
    keywords: [
      { term: "comeback", def: "When someone returns to doing something well after being away or hurt." },
      { term: "injury", def: "A hurt part of your body from an accident or too much stress." },
      { term: "tiebreak", def: "A special mini-game in tennis to decide who wins when the score is tied." },
      { term: "clay court", def: "A tennis court made of crushed clay that's slower and bouncier than other courts." },
      { term: "final", def: "The last match of a tournament, where the winner is decided." },
    ],
    quiz: [
      { q: "How long was Arthur Fils out with his injury?", options: ["2 months", "4 months", "8 months", "12 months"], a: 2 },
      { q: "What's the Barcelona Open's famous champion tradition?", options: ["Kiss the trophy", "Jump into a pool", "Plant a tree", "Ring a bell"], a: 1 },
      { q: "Who did Fils beat in the final?", options: ["Jannik Sinner", "Andrey Rublev", "Novak Djokovic", "Carlos Alcaraz"], a: 1 },
    ],
    discussion: [
      "What helps YOU come back strong when something is hard?",
      "Would you rather win a big prize or just know you did your best?",
    ],
  },
  {
    id: "apr21_madrid",
    day: 0,
    title: "Madrid Open Kicks Off Today! World No. 1 Sinner Leads the Way",
    summary: "One of tennis's biggest tournaments starts today! The Mutua Madrid Open runs from April 21 to May 3 at the Caja Mágica arena in Spain. Italy's Jannik Sinner is the top seed — the 24-year-old just won Monte Carlo, so he's in amazing form. Germany's Alexander Zverev is No. 2. Big names like Alcaraz, Djokovic, and Raducanu have all pulled out! The winner gets 1,000 ranking points — a huge boost before the French Open next month.",
    image: "https://www.atptour.com/-/media/images/news/2026/04/21/12/25/sinner-preview-madrid-2026.jpg",
    category: "Fun",
    source: "ATP Tour",
    time: "Apr 21, 2026",
    readMins: 4,
    level: "Tree",
    xp: 40,
    tag: "Sports",
    keywords: [
      { term: "tournament", def: "A series of matches where players compete to find a winner." },
      { term: "seed", def: "A player's rank in a tournament — top seeds are the best players." },
      { term: "Grand Slam", def: "The four biggest tennis tournaments in the world each year." },
      { term: "ranking points", def: "Points players earn by doing well — more points means a higher world ranking." },
      { term: "withdraw", def: "To pull out of something, like a competition, before it starts or finishes." },
    ],
    quiz: [
      { q: "Where is the Madrid Open played?", options: ["Roland Garros", "Caja Mágica", "Wimbledon", "Arthur Ashe Stadium"], a: 1 },
      { q: "Who is the No. 1 seed in Madrid?", options: ["Alcaraz", "Sinner", "Djokovic", "Zverev"], a: 1 },
      { q: "How many ranking points does the winner get?", options: ["100", "500", "1,000", "2,000"], a: 2 },
    ],
    discussion: [
      "If you were No. 1 in a sport, would you feel nervous or excited at a big match?",
      "Why might so many top players skip a tournament like Madrid?",
    ],
  },
  {
    id: "a1",
    day: 0,
    title: "Bird Lovers Asked to Pause Summer Feeding to Help Greenfinches",
    summary: "The UK's biggest bird charity, the RSPB, is asking people to stop feeding wild birds during the warm months. A tiny parasite has been spreading at bird feeders and hurting greenfinches and chaffinches — greenfinch numbers have dropped from two million to just a few hundred thousand. By feeding birds only in winter and cleaning feeders weekly, families can help these birds bounce back.",
    image: "images/article_3.webp",
    category: "Science",
    source: "BBC News",
    time: "2h ago",
    readMins: 4,
    level: "Sprout",
    xp: 30,
    tag: "Animals",
    keywords: [
      { term: "parasite", def: "A tiny living thing that lives on or inside another animal and can make it sick." },
      { term: "charity", def: "A group that helps people, animals, or nature — not a business." },
      { term: "endangered", def: "When there are so few of a kind of animal left that it might disappear." },
      { term: "habitat", def: "The natural home where a plant or animal lives." },
      { term: "spread", def: "To move from one place to many places." },
    ],
    quiz: [
      { q: "Why is the RSPB asking people to stop feeding birds in summer?", options: ["To save money", "To slow a disease spreading at feeders", "Because birds don't eat in summer", "To make people clean their gardens"], a: 1 },
      { q: "Which bird's numbers have dropped the most?", options: ["Sparrow", "Robin", "Greenfinch", "Crow"], a: 2 },
      { q: "How often should bird feeders be cleaned?", options: ["Once a year", "Weekly", "Never", "Every day"], a: 1 },
    ],
    discussion: [
      "If you had a bird feeder, would you follow this advice? Why or why not?",
      "What's one thing you can do this week to help wildlife near your home?",
    ],
  },
  {
    id: "a2",
    day: 0,
    title: "Why Scientists Just Found a Whole New Color (Sort Of!)",
    summary: "Researchers at UC Berkeley used lasers to stimulate just one kind of cell in people's eyes — and the volunteers saw a color they'd never seen before. They nicknamed it 'olo' — a super-vivid blue-green. The trick only works with special equipment, but it teaches us something cool about how our eyes and brains team up to make color.",
    image: "images/article_8.webp",
    category: "Science",
    source: "Nature",
    time: "5h ago",
    readMins: 5,
    level: "Tree",
    xp: 40,
    tag: "Discovery",
    keywords: [
      { term: "cone cells", def: "Tiny parts in your eye that help you see different colors." },
      { term: "laser", def: "A very focused beam of light." },
      { term: "stimulate", def: "To make something active or excited." },
      { term: "volunteer", def: "A person who helps with something without being paid." },
    ],
    quiz: [
      { q: "What tool did the scientists use?", options: ["A microscope", "A laser", "A telescope", "A magnifying glass"], a: 1 },
      { q: "What did they nickname the new color?", options: ["Bluey", "Greenie", "Olo", "Zorp"], a: 2 },
    ],
    discussion: ["What would you name a brand-new color if you discovered one?"],
  },
  {
    id: "a3",
    day: 1,
    title: "Giant Pandas Are No Longer 'Endangered' — But They Still Need Help",
    summary: "Thanks to years of hard work by China and conservation groups, giant pandas have been moved off the endangered species list. There are now around 1,800 wild pandas living in bamboo forests. But experts warn the job isn't finished — climate change is shrinking bamboo forests, and pandas still need protection to thrive.",
    image: "images/article_5.webp",
    category: "News",
    source: "AP News",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Animals",
    keywords: [
      { term: "conservation", def: "Protecting animals, plants, and places in nature." },
      { term: "endangered", def: "At risk of disappearing forever." },
      { term: "climate change", def: "Long-term changes in Earth's weather patterns." },
    ],
    quiz: [
      { q: "About how many wild pandas are there now?", options: ["180", "1,800", "18,000", "180,000"], a: 1 },
      { q: "What do pandas mostly eat?", options: ["Fish", "Bamboo", "Berries", "Leaves"], a: 1 },
    ],
    discussion: ["Should zoos keep pandas, or should all pandas live in the wild?"],
  },
  {
    id: "a4",
    day: 0,
    title: "Kids in Kenya Invent a Solar-Powered Water Cleaner",
    summary: "A team of 12-year-olds in Nairobi built a small device that uses sunshine to clean dirty water. Their invention won first place at a young inventors' fair. The team says they got the idea after seeing neighbors walk miles for clean water. Engineers are now helping them turn it into something families can use at home.",
    image: "images/article_9.webp",
    category: "Fun",
    source: "Kid Reporter",
    time: "3h ago",
    readMins: 3,
    level: "Sprout",
    xp: 25,
    tag: "Invention",
    keywords: [
      { term: "solar", def: "Something that runs on energy from the sun." },
      { term: "engineer", def: "Someone who designs and builds machines or structures." },
      { term: "invention", def: "A new thing someone creates for the first time." },
    ],
    quiz: [
      { q: "What powers the device?", options: ["Batteries", "The sun", "Wind", "Gasoline"], a: 1 },
    ],
    discussion: ["If you could invent something to help your community, what would it be?"],
  },
  {
    id: "a5",
    day: 0,
    title: "A Tiny Robot Swam Inside a Volcano to Study How Earth Works",
    summary: "A new underwater robot called LAVA-1 dove into a volcanic vent deep under the ocean. Cameras and sensors sent back pictures of strange glowing creatures and super-hot water that shoots up from cracks in the ocean floor. Scientists hope the robot will help us understand how our planet stays alive inside.",
    image: "images/article_10.webp",
    category: "Science",
    source: "Nat Geo",
    time: "6h ago",
    readMins: 5,
    level: "Sprout",
    xp: 30,
    tag: "Exploration",
    keywords: [
      { term: "vent", def: "An opening where gases or hot water escape from inside the Earth." },
      { term: "sensor", def: "A device that detects something — like heat, light, or movement." },
      { term: "ecosystem", def: "A group of living things and their environment that work together." },
    ],
    quiz: [
      { q: "What is LAVA-1?", options: ["A volcano", "A fish", "An underwater robot", "A submarine pilot"], a: 2 },
    ],
    discussion: ["Would you rather explore deep oceans or outer space? Why?"],
  },
  {
    id: "a6",
    day: 0,
    title: "A 9-Year-Old Just Broke the World Rubik's Cube Record",
    summary: "Leo from Tokyo solved a 3x3 Rubik's Cube in just 3.47 seconds at a speedcubing tournament. That's faster than the time it takes to tie a shoelace! Leo started cubing when he was 5 and practices about 30 minutes every day. His tip? 'Don't get frustrated. Just keep turning.'",
    image: "images/article_2.webp",
    category: "Fun",
    source: "WCA",
    time: "8h ago",
    readMins: 3,
    level: "Sprout",
    xp: 20,
    tag: "Sports",
    keywords: [
      { term: "tournament", def: "A big contest where lots of people compete." },
      { term: "record", def: "The best result ever — nobody has beaten it yet." },
    ],
    quiz: [
      { q: "How old is Leo?", options: ["7", "9", "11", "13"], a: 1 },
      { q: "How long did it take him?", options: ["3.47 seconds", "34.7 seconds", "1 minute", "30 seconds"], a: 0 },
    ],
    discussion: ["What skill would you love to be a world champion at?"],
  },
  {
    id: "a7",
    day: 0,
    title: "New James Webb Telescope Pictures Show 13 Billion Year Old Stars",
    summary: "NASA's James Webb Space Telescope sent back pictures of some of the very first stars ever to exist in the universe. The light from these stars took 13 billion years to reach Earth — which means we're basically looking back in time. Scientists say these stars formed soon after the Big Bang.",
    image: "images/article_7.webp",
    category: "Science",
    source: "NASA",
    time: "12h ago",
    readMins: 5,
    level: "Tree",
    xp: 45,
    tag: "Space",
    keywords: [
      { term: "telescope", def: "A tool that lets you see things that are very far away." },
      { term: "galaxy", def: "A huge group of stars, planets, and dust held together by gravity." },
      { term: "Big Bang", def: "The moment scientists think the universe began, a long long time ago." },
    ],
    quiz: [
      { q: "How long did the starlight take to reach us?", options: ["13 years", "13,000 years", "13 million years", "13 billion years"], a: 3 },
    ],
    discussion: ["If you could visit any planet or star, where would you go?"],
  },
  {
    id: "a8",
    day: 1,
    title: "Why a City in Spain Is Painting Its Streets White",
    summary: "The city of Seville is painting its roads and sidewalks bright white to fight summer heat. Dark streets soak up sunshine and stay hot at night. White streets bounce the sun away and stay cooler. Early tests show streets can be up to 15°F cooler — which means less need for air conditioning and happier neighborhoods.",
    image: "images/article_1.webp",
    category: "News",
    source: "Reuters",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 30,
    tag: "Planet",
    keywords: [
      { term: "reflect", def: "To bounce light (or heat) back instead of soaking it in." },
      { term: "heat wave", def: "A stretch of unusually hot weather." },
      { term: "urban", def: "Having to do with cities." },
    ],
    quiz: [
      { q: "Why are the streets being painted white?", options: ["For decoration", "To reflect heat", "For a movie", "To clean them"], a: 1 },
    ],
    discussion: ["What's one simple change that could make your town better?"],
  },
  {
    id: "a9",
    day: 2,
    title: "Meet the World's Oldest Known Tree — 5,067 Years Old",
    summary: "High in California's White Mountains lives a bristlecone pine tree nicknamed 'Methuselah.' Scientists counted its rings and believe it's over 5,000 years old — older than the pyramids of Egypt. The tree's exact location is kept secret to protect it from visitors.",
    image: "images/article_6.webp",
    category: "Science",
    source: "Smithsonian",
    time: "2d ago",
    readMins: 3,
    level: "Sprout",
    xp: 20,
    tag: "Nature",
    keywords: [
      { term: "rings", def: "Circles inside a tree trunk — each one is usually one year of growth." },
      { term: "ancient", def: "Very, very old." },
    ],
    quiz: [
      { q: "How old is Methuselah?", options: ["500", "5,067", "50,000", "500,000"], a: 1 },
    ],
    discussion: ["If you planted a tree today, who do you hope will see it in 100 years?"],
  },
  {
    id: "a10",
    day: 1,
    title: "Why the Internet Is Obsessed With This Dancing Cockatoo",
    summary: "A cockatoo named Snowball has become famous online for dancing perfectly to pop music. Scientists studying him say Snowball can change his moves to match the beat — something very few animals can do. It turns out birds that learn to talk (like parrots) might also be able to feel rhythm.",
    image: "images/article_4.webp",
    category: "Fun",
    source: "Kid Reporter",
    time: "1d ago",
    readMins: 3,
    level: "Sprout",
    xp: 20,
    tag: "Animals",
    keywords: [
      { term: "rhythm", def: "A repeating pattern in music — the beat." },
      { term: "mimic", def: "To copy someone or something." },
    ],
    quiz: [
      { q: "What makes Snowball special?", options: ["He sings", "He dances to the beat", "He paints", "He can fly far"], a: 1 },
    ],
    discussion: ["What's your favorite song to dance to?"],
  },
  {
    id: "a100",
    day: 1,
    title: "Voters Pick First Kid Mayor (Sprout)",
    summary: "For the first time, a town in Colombia elected a twelve-year-old as its Kid Mayor. The winner, Sofia, ran on a simple promise: safer parks and better lunch in schools. Real city officials have agreed to meet her team once a month to help make her ideas happen.",
    image: "images/article_1.webp",
    category: "News",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a101",
    day: 1,
    title: "Metro Opens New Green Line (Sprout)",
    summary: "A shiny new subway line rolled out this morning, carrying 40,000 commuters on its first day. The Green Line runs entirely on electricity from solar farms outside the city, making it one of the cleanest train rides in the country. Riders say the stations feel like little art galleries.",
    image: "images/article_2.webp",
    category: "News",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a102",
    day: 1,
    title: "Beach Cleanup Breaks Record (Tree)",
    summary: "Over 5,000 volunteers showed up at a single beach in Mumbai and pulled out 120 tonnes of plastic in just one weekend — a new world record. Most of it was bottles, food wrappers, and fishing line. Organisers say cleanups like this are small wins in a much bigger fight.",
    image: "images/article_3.webp",
    category: "News",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a103",
    day: 1,
    title: "Tiny Frog Glows in Dark (Sprout)",
    summary: "Biologists in Brazil discovered a pea-sized frog whose skin glows soft green under moonlight. The trick comes from special pigments that absorb daylight and release it slowly at night. Researchers think the glow helps frogs find each other in the rainforest without calling.",
    image: "images/article_4.webp",
    category: "Science",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a104",
    day: 1,
    title: "Ocean Plastic Eating Bug (Sprout)",
    summary: "A team in Japan bred a strain of bacteria that chews through plastic bottles in under a week. The bugs break the plastic into harmless sugars that fish and microbes can eat. Cleanup boats may carry tanks of them into the Pacific by 2028.",
    image: "images/article_5.webp",
    category: "Science",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a105",
    day: 1,
    title: "Kids Build Mini Satellite (Tree)",
    summary: "Ten middle schoolers in Chile built a shoebox-sized satellite called Chasqui that will measure air pollution from orbit. SpaceX launched it last Friday. Every day the kids get new data on their phones and share maps with their town's city council.",
    image: "images/article_6.webp",
    category: "Science",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a106",
    day: 1,
    title: "Giant Lego Tower Record (Sprout)",
    summary: "Schoolkids in Budapest glued together 700,000 Lego bricks to build a 120-foot tower, setting a new world record. Volunteers took turns climbing cherry-pickers for ten days straight. The money they raised went to a children's hospital next door to the event.",
    image: "images/article_7.webp",
    category: "Fun",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a107",
    day: 1,
    title: "12-Year-Old Chess Champ (Sprout)",
    summary: "Divya Deshmukh, twelve, just became the youngest grandmaster in women's chess history after winning a tense final in Chennai. She beat a player twice her age in just 23 moves. Her favorite opening, she says, is whichever one surprises her opponent.",
    image: "images/article_8.webp",
    category: "Fun",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a108",
    day: 1,
    title: "Kid Choir Goes Viral (Tree)",
    summary: "A 40-kid choir from Soweto posted themselves singing Queen's 'Bohemian Rhapsody' in four-part harmony — and the video hit 200 million views in a week. A record label flew out to sign them. The kids say they still meet at recess, like always.",
    image: "images/article_9.webp",
    category: "Fun",
    source: "Archive",
    time: "1d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a109",
    day: 2,
    title: "Metro Opens New Green Line (Sprout)",
    summary: "A shiny new subway line rolled out this morning, carrying 40,000 commuters on its first day. The Green Line runs entirely on electricity from solar farms outside the city, making it one of the cleanest train rides in the country. Riders say the stations feel like little art galleries.",
    image: "images/article_10.webp",
    category: "News",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a110",
    day: 2,
    title: "Beach Cleanup Breaks Record (Sprout)",
    summary: "Over 5,000 volunteers showed up at a single beach in Mumbai and pulled out 120 tonnes of plastic in just one weekend — a new world record. Most of it was bottles, food wrappers, and fishing line. Organisers say cleanups like this are small wins in a much bigger fight.",
    image: "images/article_1.webp",
    category: "News",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a111",
    day: 2,
    title: "Teachers Win Big Award (Tree)",
    summary: "Three teachers from small towns in Kenya, Brazil, and Japan shared this year's Global Teacher Prize. They were picked from 8,000 names for inventing new ways to help shy students speak up. Each will receive $1 million to spend on their classrooms and ideas.",
    image: "images/article_2.webp",
    category: "News",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a112",
    day: 2,
    title: "Ocean Plastic Eating Bug (Sprout)",
    summary: "A team in Japan bred a strain of bacteria that chews through plastic bottles in under a week. The bugs break the plastic into harmless sugars that fish and microbes can eat. Cleanup boats may carry tanks of them into the Pacific by 2028.",
    image: "images/article_3.webp",
    category: "Science",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a113",
    day: 2,
    title: "Kids Build Mini Satellite (Sprout)",
    summary: "Ten middle schoolers in Chile built a shoebox-sized satellite called Chasqui that will measure air pollution from orbit. SpaceX launched it last Friday. Every day the kids get new data on their phones and share maps with their town's city council.",
    image: "images/article_4.webp",
    category: "Science",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a114",
    day: 2,
    title: "Bees Dance Math Code (Tree)",
    summary: "Scientists decoded the wiggly dance honeybees do when they find flowers — and it's basically math. The angle tells direction, the rhythm tells distance. Researchers trained a robot bee to dance the code and real bees believed her. Hives might be smarter than we thought.",
    image: "images/article_5.webp",
    category: "Science",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a115",
    day: 2,
    title: "12-Year-Old Chess Champ (Sprout)",
    summary: "Divya Deshmukh, twelve, just became the youngest grandmaster in women's chess history after winning a tense final in Chennai. She beat a player twice her age in just 23 moves. Her favorite opening, she says, is whichever one surprises her opponent.",
    image: "images/article_6.webp",
    category: "Fun",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a116",
    day: 2,
    title: "Kid Choir Goes Viral (Sprout)",
    summary: "A 40-kid choir from Soweto posted themselves singing Queen's 'Bohemian Rhapsody' in four-part harmony — and the video hit 200 million views in a week. A record label flew out to sign them. The kids say they still meet at recess, like always.",
    image: "images/article_7.webp",
    category: "Fun",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a117",
    day: 2,
    title: "Tokyo Cat Cafe Opens (Tree)",
    summary: "A new Tokyo cafe lets visitors sip milk tea surrounded by ten rescue cats looking for homes. Half the profits pay vet bills; the other half buy food for city strays. In its first month, fourteen cats found new families through the cafe.",
    image: "images/article_8.webp",
    category: "Fun",
    source: "Archive",
    time: "2d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a118",
    day: 3,
    title: "Beach Cleanup Breaks Record (Sprout)",
    summary: "Over 5,000 volunteers showed up at a single beach in Mumbai and pulled out 120 tonnes of plastic in just one weekend — a new world record. Most of it was bottles, food wrappers, and fishing line. Organisers say cleanups like this are small wins in a much bigger fight.",
    image: "images/article_9.webp",
    category: "News",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a119",
    day: 3,
    title: "Teachers Win Big Award (Sprout)",
    summary: "Three teachers from small towns in Kenya, Brazil, and Japan shared this year's Global Teacher Prize. They were picked from 8,000 names for inventing new ways to help shy students speak up. Each will receive $1 million to spend on their classrooms and ideas.",
    image: "images/article_10.webp",
    category: "News",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a120",
    day: 3,
    title: "Library Gets Robot Helper (Tree)",
    summary: "A public library in Singapore just hired Lily — a small rolling robot who finds books on tall shelves and reads picture stories to younger kids. Librarians say Lily isn't replacing them; she's the new sidekick. Visits have jumped 30 percent since she arrived.",
    image: "images/article_1.webp",
    category: "News",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a121",
    day: 3,
    title: "Kids Build Mini Satellite (Sprout)",
    summary: "Ten middle schoolers in Chile built a shoebox-sized satellite called Chasqui that will measure air pollution from orbit. SpaceX launched it last Friday. Every day the kids get new data on their phones and share maps with their town's city council.",
    image: "images/article_2.webp",
    category: "Science",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a122",
    day: 3,
    title: "Bees Dance Math Code (Sprout)",
    summary: "Scientists decoded the wiggly dance honeybees do when they find flowers — and it's basically math. The angle tells direction, the rhythm tells distance. Researchers trained a robot bee to dance the code and real bees believed her. Hives might be smarter than we thought.",
    image: "images/article_3.webp",
    category: "Science",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a123",
    day: 3,
    title: "Sun Flare Paints Sky (Tree)",
    summary: "A powerful solar flare hit Earth's magnetic bubble this week, painting green and purple auroras as far south as Texas. Phones mostly kept working. Scientists say flares like this one help us understand how to protect satellites during a bigger solar storm.",
    image: "images/article_4.webp",
    category: "Science",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a124",
    day: 3,
    title: "Kid Choir Goes Viral (Sprout)",
    summary: "A 40-kid choir from Soweto posted themselves singing Queen's 'Bohemian Rhapsody' in four-part harmony — and the video hit 200 million views in a week. A record label flew out to sign them. The kids say they still meet at recess, like always.",
    image: "images/article_5.webp",
    category: "Fun",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a125",
    day: 3,
    title: "Tokyo Cat Cafe Opens (Sprout)",
    summary: "A new Tokyo cafe lets visitors sip milk tea surrounded by ten rescue cats looking for homes. Half the profits pay vet bills; the other half buy food for city strays. In its first month, fourteen cats found new families through the cafe.",
    image: "images/article_6.webp",
    category: "Fun",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a126",
    day: 3,
    title: "Sneaker Art Show Wins (Tree)",
    summary: "Thirteen-year-old Amina from Lagos turned old sneakers into tiny sculptures and won top prize at a London youth art show. One of her pieces — a pair of ruined shoes covered in gold leaf — now lives in a proper museum.",
    image: "images/article_7.webp",
    category: "Fun",
    source: "Archive",
    time: "3d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a127",
    day: 4,
    title: "Teachers Win Big Award (Sprout)",
    summary: "Three teachers from small towns in Kenya, Brazil, and Japan shared this year's Global Teacher Prize. They were picked from 8,000 names for inventing new ways to help shy students speak up. Each will receive $1 million to spend on their classrooms and ideas.",
    image: "images/article_8.webp",
    category: "News",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a128",
    day: 4,
    title: "Library Gets Robot Helper (Sprout)",
    summary: "A public library in Singapore just hired Lily — a small rolling robot who finds books on tall shelves and reads picture stories to younger kids. Librarians say Lily isn't replacing them; she's the new sidekick. Visits have jumped 30 percent since she arrived.",
    image: "images/article_9.webp",
    category: "News",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a129",
    day: 4,
    title: "Park Adds Mini Forest (Tree)",
    summary: "A city park in Rotterdam planted a 'tiny forest' the size of a tennis court — hundreds of native trees squeezed together so they grow extra fast. Ecologists say it will pull in birds, bees, and butterflies within two years and stay lush without a single sprinkler.",
    image: "images/article_10.webp",
    category: "News",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a130",
    day: 4,
    title: "Bees Dance Math Code (Sprout)",
    summary: "Scientists decoded the wiggly dance honeybees do when they find flowers — and it's basically math. The angle tells direction, the rhythm tells distance. Researchers trained a robot bee to dance the code and real bees believed her. Hives might be smarter than we thought.",
    image: "images/article_1.webp",
    category: "Science",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a131",
    day: 4,
    title: "Sun Flare Paints Sky (Sprout)",
    summary: "A powerful solar flare hit Earth's magnetic bubble this week, painting green and purple auroras as far south as Texas. Phones mostly kept working. Scientists say flares like this one help us understand how to protect satellites during a bigger solar storm.",
    image: "images/article_2.webp",
    category: "Science",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a132",
    day: 4,
    title: "AI Reads Ancient Text (Tree)",
    summary: "An AI built by Oxford students managed to read a 2,000-year-old scroll that was too fragile to unroll. X-rays scanned the inside, and the program figured out the faint letters. The scroll turned out to be a Greek poem nobody had read since Roman times.",
    image: "images/article_3.webp",
    category: "Science",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a133",
    day: 4,
    title: "Tokyo Cat Cafe Opens (Sprout)",
    summary: "A new Tokyo cafe lets visitors sip milk tea surrounded by ten rescue cats looking for homes. Half the profits pay vet bills; the other half buy food for city strays. In its first month, fourteen cats found new families through the cafe.",
    image: "images/article_4.webp",
    category: "Fun",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a134",
    day: 4,
    title: "Sneaker Art Show Wins (Sprout)",
    summary: "Thirteen-year-old Amina from Lagos turned old sneakers into tiny sculptures and won top prize at a London youth art show. One of her pieces — a pair of ruined shoes covered in gold leaf — now lives in a proper museum.",
    image: "images/article_5.webp",
    category: "Fun",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a135",
    day: 4,
    title: "Skateboard Pup Stunt (Tree)",
    summary: "A pug named Biscuit rolled down a 30-stair handrail on a custom skateboard in California, breaking the world record for the longest dog grind. His trainer uses only treats, never tricks, and Biscuit gets a full weekend off after every new record.",
    image: "images/article_6.webp",
    category: "Fun",
    source: "Archive",
    time: "4d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a136",
    day: 5,
    title: "Library Gets Robot Helper (Sprout)",
    summary: "A public library in Singapore just hired Lily — a small rolling robot who finds books on tall shelves and reads picture stories to younger kids. Librarians say Lily isn't replacing them; she's the new sidekick. Visits have jumped 30 percent since she arrived.",
    image: "images/article_7.webp",
    category: "News",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a137",
    day: 5,
    title: "Park Adds Mini Forest (Sprout)",
    summary: "A city park in Rotterdam planted a 'tiny forest' the size of a tennis court — hundreds of native trees squeezed together so they grow extra fast. Ecologists say it will pull in birds, bees, and butterflies within two years and stay lush without a single sprinkler.",
    image: "images/article_8.webp",
    category: "News",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a138",
    day: 5,
    title: "City Plants 10,000 Trees (Tree)",
    summary: "Volunteers across the city planted 10,000 young trees this weekend to make the air cleaner and cooler for summer. Scientists say the new leaves will soak up tons of carbon dioxide and shade hot streets, while kids from local schools helped water the roots on day one.",
    image: "images/article_9.webp",
    category: "News",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a139",
    day: 5,
    title: "Sun Flare Paints Sky (Sprout)",
    summary: "A powerful solar flare hit Earth's magnetic bubble this week, painting green and purple auroras as far south as Texas. Phones mostly kept working. Scientists say flares like this one help us understand how to protect satellites during a bigger solar storm.",
    image: "images/article_10.webp",
    category: "Science",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a140",
    day: 5,
    title: "AI Reads Ancient Text (Sprout)",
    summary: "An AI built by Oxford students managed to read a 2,000-year-old scroll that was too fragile to unroll. X-rays scanned the inside, and the program figured out the faint letters. The scroll turned out to be a Greek poem nobody had read since Roman times.",
    image: "images/article_1.webp",
    category: "Science",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a141",
    day: 5,
    title: "Mars Rover Finds Water Hint (Tree)",
    summary: "NASA's Perseverance rover scraped a rock on Mars and found tiny mineral veins that form only when water trickles through stone. Scientists aren't saying there's life — yet — but they admit the chemistry is suspiciously good. The next rover will bring these rocks home in 2033.",
    image: "images/article_2.webp",
    category: "Science",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a142",
    day: 5,
    title: "Sneaker Art Show Wins (Sprout)",
    summary: "Thirteen-year-old Amina from Lagos turned old sneakers into tiny sculptures and won top prize at a London youth art show. One of her pieces — a pair of ruined shoes covered in gold leaf — now lives in a proper museum.",
    image: "images/article_3.webp",
    category: "Fun",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a143",
    day: 5,
    title: "Skateboard Pup Stunt (Sprout)",
    summary: "A pug named Biscuit rolled down a 30-stair handrail on a custom skateboard in California, breaking the world record for the longest dog grind. His trainer uses only treats, never tricks, and Biscuit gets a full weekend off after every new record.",
    image: "images/article_4.webp",
    category: "Fun",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a144",
    day: 5,
    title: "Corgi Wins Pancake Race (Tree)",
    summary: "Bramble the corgi waddled to victory in England's yearly Pancake Race, beating three border collies and a golden retriever. Dogs and owners hop down the street while flipping pancakes in a pan. Bramble's secret, his owner says, was tiny legs and pure focus.",
    image: "images/article_5.webp",
    category: "Fun",
    source: "Archive",
    time: "5d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a145",
    day: 6,
    title: "Park Adds Mini Forest (Sprout)",
    summary: "A city park in Rotterdam planted a 'tiny forest' the size of a tennis court — hundreds of native trees squeezed together so they grow extra fast. Ecologists say it will pull in birds, bees, and butterflies within two years and stay lush without a single sprinkler.",
    image: "images/article_6.webp",
    category: "News",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a146",
    day: 6,
    title: "City Plants 10,000 Trees (Sprout)",
    summary: "Volunteers across the city planted 10,000 young trees this weekend to make the air cleaner and cooler for summer. Scientists say the new leaves will soak up tons of carbon dioxide and shade hot streets, while kids from local schools helped water the roots on day one.",
    image: "images/article_7.webp",
    category: "News",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a147",
    day: 6,
    title: "Voters Pick First Kid Mayor (Tree)",
    summary: "For the first time, a town in Colombia elected a twelve-year-old as its Kid Mayor. The winner, Sofia, ran on a simple promise: safer parks and better lunch in schools. Real city officials have agreed to meet her team once a month to help make her ideas happen.",
    image: "images/article_8.webp",
    category: "News",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a148",
    day: 6,
    title: "AI Reads Ancient Text (Sprout)",
    summary: "An AI built by Oxford students managed to read a 2,000-year-old scroll that was too fragile to unroll. X-rays scanned the inside, and the program figured out the faint letters. The scroll turned out to be a Greek poem nobody had read since Roman times.",
    image: "images/article_9.webp",
    category: "Science",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a149",
    day: 6,
    title: "Mars Rover Finds Water Hint (Sprout)",
    summary: "NASA's Perseverance rover scraped a rock on Mars and found tiny mineral veins that form only when water trickles through stone. Scientists aren't saying there's life — yet — but they admit the chemistry is suspiciously good. The next rover will bring these rocks home in 2033.",
    image: "images/article_10.webp",
    category: "Science",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a150",
    day: 6,
    title: "Tiny Frog Glows in Dark (Tree)",
    summary: "Biologists in Brazil discovered a pea-sized frog whose skin glows soft green under moonlight. The trick comes from special pigments that absorb daylight and release it slowly at night. Researchers think the glow helps frogs find each other in the rainforest without calling.",
    image: "images/article_1.webp",
    category: "Science",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a151",
    day: 6,
    title: "Skateboard Pup Stunt (Sprout)",
    summary: "A pug named Biscuit rolled down a 30-stair handrail on a custom skateboard in California, breaking the world record for the longest dog grind. His trainer uses only treats, never tricks, and Biscuit gets a full weekend off after every new record.",
    image: "images/article_2.webp",
    category: "Fun",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a152",
    day: 6,
    title: "Corgi Wins Pancake Race (Sprout)",
    summary: "Bramble the corgi waddled to victory in England's yearly Pancake Race, beating three border collies and a golden retriever. Dogs and owners hop down the street while flipping pancakes in a pan. Bramble's secret, his owner says, was tiny legs and pure focus.",
    image: "images/article_3.webp",
    category: "Fun",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a153",
    day: 6,
    title: "Giant Lego Tower Record (Tree)",
    summary: "Schoolkids in Budapest glued together 700,000 Lego bricks to build a 120-foot tower, setting a new world record. Volunteers took turns climbing cherry-pickers for ten days straight. The money they raised went to a children's hospital next door to the event.",
    image: "images/article_4.webp",
    category: "Fun",
    source: "Archive",
    time: "6d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a154",
    day: 0,
    title: "Clean Water for Village",
    summary: "A small village in Uganda got its first clean-water well this week. Kids no longer walk two hours to fetch water before school. A charity paid for the pipes, and the town's own builders dug the well by hand over just six weeks.",
    image: "images/article_5.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a155",
    day: 0,
    title: "Friendly Dog Helps Kids Read",
    summary: "A library in Scotland hired Milo, a very calm labrador, to sit beside shy kids while they practise reading out loud. Dogs don't judge if you stumble on a word. Teachers say kids who spend time with Milo gain confidence twice as fast.",
    image: "images/article_6.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a156",
    day: 0,
    title: "New Playground Opens Downtown",
    summary: "A new playground opened beside City Hall this weekend — designed by a group of local seven-year-olds. It has a tall climbing pyramid, a swing shaped like a moon, and a sandbox with real dinosaur bone casts to dig up.",
    image: "images/article_7.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a157",
    day: 0,
    title: "Wind Farm Powers 10,000 Homes",
    summary: "Fifty tall wind turbines spun to life off the coast of Portugal this week, quietly sending clean power to 10,000 homes. Each blade is as long as a jumbo jet. Fishermen say porpoises have already started swimming around the bases to hunt for fish.",
    image: "images/article_8.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a158",
    day: 0,
    title: "City Council Bans Plastic Bags",
    summary: "The city council in Melbourne voted this week to ban single-use plastic bags in every shop. Small stores get free cloth bags to hand out. Supporters say the city already collects 40 percent less plastic waste after trying the rule in a few neighbourhoods last year.",
    image: "images/article_9.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a159",
    day: 0,
    title: "Scientists Map New Ocean Zone",
    summary: "Researchers on a submarine mapped a stretch of seafloor no human had ever seen — a canyon near Greenland as deep as the Grand Canyon is tall. They spotted glass sponges, ghost octopuses, and strange little shrimp that have no eyes.",
    image: "images/article_10.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a160",
    day: 0,
    title: "Students Lead Climate March",
    summary: "Over a million students in 70 countries left school for a day to march for stronger climate action. They sang, carried homemade signs, and delivered letters to their local leaders. Several governments promised to meet with youth groups before the end of the month.",
    image: "images/article_1.webp",
    category: "News",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a161",
    day: 0,
    title: "Baby Turtles Race to Sea",
    summary: "Hundreds of tiny sea turtles hatched on a protected beach in Costa Rica last night and scrambled toward the waves. Rangers cleared a path and switched off streetlights so the babies wouldn't get lost. Out of 400 hatchlings, 380 made it safely into the surf.",
    image: "images/article_2.webp",
    category: "Science",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a162",
    day: 0,
    title: "Cloud Shapes Kids Can Name",
    summary: "Meteorologists launched a kid-friendly cloud guide this week, with silly names like 'pancake', 'mashed potato', and 'dragon'. Real scientific names are hard. The guide comes with a paper cloud-spotter you can print and take outside to match the sky to the pictures.",
    image: "images/article_3.webp",
    category: "Science",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a163",
    day: 0,
    title: "Bees Help Mango Farms Grow",
    summary: "Researchers in India discovered that adding beehives near mango trees makes the harvest 40 percent bigger. The bees pollinate the flowers that birds and butterflies miss. Farmers are now renting hives the same way they rent tractors, and local honey sales are booming.",
    image: "images/article_4.webp",
    category: "Science",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a164",
    day: 0,
    title: "Skateboarding Robot Wins Contest",
    summary: "A college team in Tokyo built a wobbly skateboarding robot named Kuri that actually won a tricks contest against human beginners. It pulled off a kickflip — crashed — and did it again cleanly on the second try. Kuri's creators say their next project is a surfing robot.",
    image: "images/article_5.webp",
    category: "Fun",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a165",
    day: 0,
    title: "Giant Chocolate Egg Unveiled",
    summary: "A bakery in Belgium unveiled a 15-foot-tall chocolate egg for Easter, carved with hundreds of tiny animals. It weighs over a ton and took six chefs three weeks of work. After the holiday the egg will be broken up and the pieces sent to food banks across the country.",
    image: "images/article_6.webp",
    category: "Fun",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a166",
    day: 0,
    title: "Young Violinist Plays Concert Hall",
    summary: "Twelve-year-old Nia from Atlanta played a full hour of music with the London Symphony this Sunday — the youngest soloist the orchestra has ever invited. She picked a modern piece written by a 19-year-old composer. The audience gave three standing ovations.",
    image: "images/article_7.webp",
    category: "Fun",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a167",
    day: 0,
    title: "Kite Festival Breaks Sky Record",
    summary: "Six thousand kites lifted off together at a festival in Gujarat, India, setting a new world record for the biggest kite sky. Kids made most of them from bamboo and old plastic bags. Judges flew a drone up to count every kite — and it was nearly bumped out of the air.",
    image: "images/article_8.webp",
    category: "Fun",
    source: "Archive",
    time: "0d ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a200",
    day: 0,
    title: "Ocean Rescue Team Saves Whale",
    summary: "A rescue team in New Zealand untangled a humpback whale caught in fishing nets off the coast this morning. Using small boats and sharp knives on long poles, they worked for four hours while the calm whale watched. Everyone cheered when she swam free with a flick of her tail.",
    image: "images/article_1.webp",
    category: "News",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a201",
    day: 0,
    title: "Global Leaders Meet on Climate Pact",
    summary: "World leaders gathered in Rio this week to hammer out a new climate deal. After long nights of talk, 82 countries agreed to cut their use of coal by half over the next decade. Young activists outside called it a good step, but not nearly fast enough.",
    image: "images/article_2.webp",
    category: "News",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "News",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["News", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a202",
    day: 0,
    title: "Quantum Computer Hits New Milestone",
    summary: "A Canadian lab ran a quantum computer for a full hour without a single error — a first in the field. Quantum machines promise to solve problems that regular computers would take centuries to crunch, like designing new medicines and breaking old codes.",
    image: "images/article_3.webp",
    category: "Science",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a203",
    day: 0,
    title: "Ladybug Army Saves a Farm",
    summary: "Farmers in Italy released a million ladybugs onto their tomato fields to eat pests — no sprays needed. The red beetles gobbled up aphids for three weeks and then flew off to nearby meadows. The tomatoes this year, farmers say, taste sweeter than ever.",
    image: "images/article_4.webp",
    category: "Science",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Science",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Science", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a204",
    day: 0,
    title: "Puppy Learns to Skateboard",
    summary: "A golden retriever puppy named Sunny learned to push a skateboard with one paw before she was five months old. Her trainer put peanut butter on the nose of the board to coax the first move. Sunny now has her own tiny helmet and half a million fans online.",
    image: "images/article_5.webp",
    category: "Fun",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a205",
    day: 0,
    title: "Kid Inventor Builds Pancake Robot",
    summary: "Twelve-year-old Kenji from Osaka glued together Lego Technic and an old motor to build a robot that flips pancakes perfectly every time. He built it because his little brother kept burning breakfast. The design is now shared online so any kid can try to make one.",
    image: "images/article_6.webp",
    category: "Fun",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Sprout",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
  {
    id: "a206",
    day: 0,
    title: "Young Pianist Wins World Stage",
    summary: "Eleven-year-old Lila from Paris won the junior piano finals in Warsaw this weekend, beating teenagers twice her age. She picked a tricky Chopin piece and played without sheet music. Her prize is a scholarship to study with a famous pianist for the next two summers.",
    image: "images/article_7.webp",
    category: "Fun",
    source: "Today's Edition",
    time: "1h ago",
    readMins: 4,
    level: "Tree",
    xp: 25,
    tag: "Fun",
    keywords: [{ term: "learn", def: "To find out about something new." }],
    quiz: [{ q: "What is this story about?", options: ["Fun", "Nothing", "Sports", "Food"], a: 0 }],
    discussion: ["What did you find most surprising?"]
  },
];

const CATEGORIES = [
  { id: "news", label: "News", emoji: "📰", color: "#ff6b5b", bg: "#ffece8" },
  { id: "science", label: "Science", emoji: "🔬", color: "#17b3a6", bg: "#e0f6f3" },
  { id: "fun", label: "Fun", emoji: "🎈", color: "#9061f9", bg: "#eee5ff" },
];

const LEVELS = [
  { id: "Sprout", emoji: "🌱", label: "Sprout", sub: "Ages 8–9" },
  { id: "Sprout", emoji: "🌾", label: "Sprout", sub: "Ages 10–11" },
  { id: "Tree", emoji: "🌳", label: "Tree", sub: "Ages 12–13" },
];

// Mock user state
const MOCK_USER = {
  name: "Mia",
  streak: 7,
  minutesToday: 6,
  dailyGoal: 15,
  totalXp: 1240,
  weekXp: 310,
  badges: ["🦉", "🔭", "🌱"],
  readToday: ["a2"], // already read
};

window.ARTICLES = ARTICLES;
window.CATEGORIES = CATEGORIES;
window.LEVELS = LEVELS;
window.MOCK_USER = MOCK_USER;
